import { ChapterConfig } from '../engine/types';

export const elasticityChapter: ChapterConfig = {
  id: 'chapter-elasticity',
  title: 'Price Elasticity of Demand',
  description:
    'Understand how sensitive quantity demanded is to price changes. Explore elastic, inelastic, and unit elastic demand curves.',
  themeColor: '#0066B3',
  graphThemeId: 'textbook',
  graphType: 'elasticity',
  showTable: false,
  tablePosition: 'none',
  xAxis: {
    label: 'Quantity',
    min: 0,
    max: 12,
    ticks: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  },
  yAxis: {
    label: 'Price',
    min: 0,
    max: 12,
    ticks: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  },
  curves: [
    {
      id: 'perfectly-inelastic',
      label: 'Perfectly Inelastic (e=0)',
      curveType: 'perfectly-inelastic',
      params: { slope: 0, intercept: 6 },
      colorRole: 'supplyInitial',
      visible: false,
      animated: true,
    },
    {
      id: 'inelastic',
      label: 'Inelastic (0<e<1)',
      curveType: 'inelastic',
      params: { slope: -0.3, intercept: 8 },
      colorRole: 'curveOrange',
      visible: false,
      animated: true,
    },
    {
      id: 'unit-elastic',
      label: 'Unit Elastic (e=1)',
      curveType: 'unit-elastic',
      params: { elasticity: 1, baseQ: 6, baseP: 4 },
      colorRole: 'curveBlue',
      visible: false,
      animated: true,
    },
    {
      id: 'elastic',
      label: 'Elastic (e>1)',
      curveType: 'elastic',
      params: { slope: -1.5, intercept: 12 },
      colorRole: 'curveGreen',
      visible: false,
      animated: true,
    },
    {
      id: 'perfectly-elastic',
      label: 'Perfectly Elastic (e→∞)',
      curveType: 'perfectly-elastic',
      params: { slope: 0, intercept: 5 },
      colorRole: 'curveViolet',
      visible: false,
      animated: true,
    },
  ],
  buildSteps: [
    {
      id: 'elastic-intro',
      title: 'Introduction to Elasticity',
      description: 'Price elasticity of demand measures how responsive quantity demanded is to a change in price.',
      visibleLayers: [],
    },
    {
      id: 'perfectly-inelastic-step',
      title: 'Perfectly Inelastic (e=0)',
      description: 'Quantity does not change with price. Example: life-saving medications.',
      visibleLayers: ['perfectly-inelastic'],
    },
    {
      id: 'inelastic-step',
      title: 'Inelastic (0<e<1)',
      description: 'Quantity changes by a smaller % than price. Example: gasoline, basic groceries.',
      visibleLayers: ['inelastic'],
    },
    {
      id: 'unit-elastic-step',
      title: 'Unit Elastic (e=1)',
      description: 'Quantity changes by the same % as price. A middle ground between elastic and inelastic.',
      visibleLayers: ['unit-elastic'],
    },
    {
      id: 'elastic-step',
      title: 'Elastic (e>1)',
      description: 'Quantity changes by a larger % than price. Example: luxury goods, entertainment.',
      visibleLayers: ['elastic'],
    },
    {
      id: 'perfectly-elastic-step',
      title: 'Perfectly Elastic (e→∞)',
      description: 'Any price increase causes quantity demanded to drop to zero. Example: commodities in perfect competition.',
      visibleLayers: ['perfectly-elastic'],
    },
  ],
  animationSteps: [
    { id: 'animate-1', title: 'Perfectly Inelastic', durationMs: 1000, layerIds: ['perfectly-inelastic'] },
    { id: 'animate-2', title: 'Inelastic', durationMs: 1000, layerIds: ['inelastic'] },
    { id: 'animate-3', title: 'Unit Elastic', durationMs: 1000, layerIds: ['unit-elastic'] },
    { id: 'animate-4', title: 'Elastic', durationMs: 1000, layerIds: ['elastic'] },
    { id: 'animate-5', title: 'Perfectly Elastic', durationMs: 1000, layerIds: ['perfectly-elastic'] },
  ],
  exploreControls: [
    {
      id: 'elasticity-slider',
      label: 'Elasticity Level',
      type: 'slider',
      min: 0,
      max: 4,
      step: 1,
      defaultValue: 2,
      targetKey: 'elasticity',
    },
    {
      id: 'price-change',
      label: 'Price Change Scenario',
      type: 'button',
      defaultValue: false,
      targetKey: 'showPriceChange',
    },
  ],
  exploreScenarios: [
    {
      id: 'elasticity-0',
      label: 'Perfectly Inelastic',
      description: 'No response to price change',
    },
    {
      id: 'elasticity-1',
      label: 'Inelastic',
      description: 'Small response to price change',
    },
    {
      id: 'elasticity-2',
      label: 'Unit Elastic',
      description: 'Proportional response to price change',
    },
    {
      id: 'elasticity-3',
      label: 'Elastic',
      description: 'Large response to price change',
    },
    {
      id: 'elasticity-4',
      label: 'Perfectly Elastic',
      description: 'Infinite response to price change',
    },
  ],
  curveLabels: [
    { curveId: 'perfectly-inelastic', text: 'e=0', x: 7, y: 2 },
    { curveId: 'inelastic', text: '0<e<1', x: 10, y: 2 },
    { curveId: 'unit-elastic', text: 'e=1', x: 8, y: 2 },
    { curveId: 'elastic', text: 'e>1', x: 11, y: 2 },
    { curveId: 'perfectly-elastic', text: 'e→∞', x: 6, y: 1 },
  ],
  modeContent: {
    book: 'Price elasticity of demand (PED) measures the responsiveness of quantity demanded to changes in price. It ranges from perfectly inelastic (e=0) to perfectly elastic (e→∞).',
  },
};
