import { ChapterConfig } from '../engine/types';

/** Q on x-axis (7–13), P on y-axis (0–2); smooth curves via `throughPoints`. */
export const increaseInSupplyChapter: ChapterConfig = {
  id: 'chapter-increase-in-supply',
  title: 'An Increase in Supply',
  description:
    'See how a rightward shift in supply lowers equilibrium price and raises equilibrium quantity, holding demand constant.',
  themeColor: '#0066B3',
  graphThemeId: 'textbook',
  graphLayout: { equalAxisLengths: true },
  graphType: 'supply-demand',
  bookBuildStepId: 'step-5',
  showTable: false,
  tablePosition: 'none',
  xAxis: {
    label: 'Quantity (millions of bottles per day)',
    min: 7,
    max: 13,
    ticks: [7, 8, 9, 10, 11, 12, 13],
    tickFormat: 'integer',
  },
  yAxis: {
    label: 'Price (dollars per bottle)',
    min: 0,
    max: 2,
    ticks: [0, 0.5, 1, 1.5, 2],
    tickFormat: 'decimal-2',
    titleRotation: 0,
    titleAboveMaxTick: true,
    titleOffsetX: -8,
    titleOffsetY: -14,
  },
  curves: [
    {
      id: 'demand',
      label: 'Demand',
      curveType: 'throughPoints',
      params: {
        points: [
          { x: 8.5, y: 1.85 },
          { x: 10, y: 1 },
          { x: 11, y: 0.75 },
          { x: 12.3, y: 0.52 },
        ],
      },
      colorRole: 'demand',
      visible: true,
      animated: true,
    },
    {
      id: 'supply-initial',
      label: 'S₀',
      curveType: 'throughPoints',
      params: {
        points: [
          { x: 9, y: 0.75 },
          { x: 10, y: 1 },
          { x: 11.5, y: 1.8 },
        ],
      },
      colorRole: 'demand',
      visible: true,
      animated: true,
    },
    {
      id: 'supply-new',
      label: 'S₁',
      curveType: 'throughPoints',
      params: {
        points: [
          { x: 10, y: 0.47 },
          { x: 11, y: 0.72 },
          { x: 12.5, y: 1.52 },
        ],
      },
      colorRole: 'supplyInitial',
      visible: false,
      animated: false,
      morphFromCurveId: 'supply-initial',
    },
  ],
  equilibria: [
    {
      id: 'initial',
      demandCurveId: 'demand',
      supplyCurveId: 'supply-initial',
      colorRole: 'equilibrium',
    },
    {
      id: 'new',
      demandCurveId: 'demand',
      supplyCurveId: 'supply-new',
      colorRole: 'supplyInitial',
    },
  ],
  exploreLayers: ['demand', 'supply-initial', 'supply-new'],
  graphArrows: [
    {
      id: 'supply-increases',
      from: { x: 11.15, y: 1.5 },
      to: { x: 12.25, y: 1.5 },
      label: 'Supply\nincreases',
      calloutColorRole: 'calloutCream',
      strokeGradient: { fromColorRole: 'demand', toColorRole: 'supplyInitial' },
      labelOffset: { x: 10.5, y: 1.7 },
    },
    {
      id: 'price-falls',
      from: { x: 7.42, y: 0.98 },
      to: { x: 7.42, y: 0.77 },
      label: 'Price\nfalls',
      calloutColorRole: 'calloutCream',
      strokeColorRole: 'priceFalls',
      labelOffset: { x: 8, y: 1.2 },
    },
    {
      id: 'quantity-increases',
      from: { x: 10.08, y: 0.13 },
      to: { x: 10.92, y: 0.13 },
      label: 'Quantity\nincreases',
      calloutColorRole: 'calloutCream',
      strokeColorRole: 'quantityIncreases',
      labelOffset: { x: 11.8, y: 0.35 },
    },
    {
      id: 'quantity-demanded-increases',
      from: { x: 10, y: 1 },
      to: { x: 11.047, y: 0.74 },
      followCurveId: 'demand',
      label: 'Quantity\ndemanded\nincreases',
      calloutColorRole: 'calloutCream',
      strokeColorRole: 'quantityDemandedIncreases',
      labelOffset: { x: 8.9, y: 0.5 },
    },
  ],
  buildSteps: [
    {
      id: 'step-1',
      title: 'Step 1: Market demand',
      description: 'Start with the demand curve (D).',
      visibleLayers: ['demand'],
    },
    {
      id: 'step-2',
      title: 'Step 2: Initial supply',
      description: 'Add the original supply curve (S₀).',
      visibleLayers: ['demand', 'supply-initial'],
    },
    {
      id: 'step-3',
      title: 'Step 3: Initial equilibrium',
      description: 'The market clears where S₀ intersects D.',
      visibleLayers: ['demand', 'supply-initial'],
      showEquilibrium: true,
      visibleEquilibria: ['initial'],
      showPriceLine: true,
      showQuantityLine: true,
    },
    {
      id: 'step-4',
      title: 'Step 4: Supply increases',
      description: 'When supply increases, the curve shifts right to S₁ (parallel to S₀).',
      visibleLayers: ['demand', 'supply-initial', 'supply-new'],
      showEquilibrium: true,
      visibleEquilibria: ['initial'],
      showPriceLine: true,
      showQuantityLine: true,
      visibleAnnotations: ['supply-increases'],
    },
    {
      id: 'step-5',
      title: 'Step 5: New equilibrium',
      description:
        'The new equilibrium (E₁) has a lower price and higher quantity than the original (E₀).',
      visibleLayers: ['demand', 'supply-initial', 'supply-new'],
      showEquilibrium: true,
      visibleEquilibria: ['initial', 'new'],
      showPriceLine: true,
      showQuantityLine: true,
      visibleAnnotations: [
        'supply-increases',
        'price-falls',
        'quantity-increases',
        'quantity-demanded-increases',
      ],
    },
  ],
  animationSteps: [
    { id: 'animate-1', title: 'Demand', durationMs: 1000, layerIds: ['demand'] },
    { id: 'animate-2', title: 'Initial supply', durationMs: 1000, layerIds: ['supply-initial'] },
    { id: 'animate-3', title: 'Supply shift', durationMs: 1200, layerIds: ['supply-new'] },
    {
      id: 'animate-4',
      title: 'Annotations',
      durationMs: 1000,
      annotationIds: [
        'supply-increases',
        'price-falls',
        'quantity-increases',
        'quantity-demanded-increases',
      ],
    },
  ],
  curveLabels: [
    { curveId: 'demand', text: 'D', x: 12.3, y: 0.52, anchor: 'start', offsetX: 0.22 },
    { curveId: 'supply-initial', text: 'S₀', x: 11.5, y: 1.75, anchor: 'start', offsetX: 0.22 },
    { curveId: 'supply-new', text: 'S₁', x: 12.5, y: 1.5, anchor: 'start', offsetX: 0.22 },
  ],
  modeContent: {
    book: '(a) An increase in supply: S shifts right along parallel supply curves; equilibrium price falls and equilibrium quantity rises.',
    animate: 'Watch D, S₀, the shift to S₁, and the textbook callout arrows.',
  },
};
