import { ChapterConfig } from '../engine/types';

/** Q on x-axis (7–13), P on y-axis (0–2.5); textbook supply reference chart. */
export const quantitySuppliedVsSupplyChapter: ChapterConfig = {
  id: 'chapter-quantity-supplied-vs-supply',
  title: 'Change in Quantity Supplied versus Change in Supply',
  description:
    'Distinguish movement along a supply curve (change in quantity supplied) from a shift of the curve (change in supply).',
  themeColor: '#DA2128',
  graphThemeId: 'textbook',
  graphLayout: { equalAxisLengths: true },
  graphType: 'supply-demand',
  bookBuildStepId: 'step-6',
  showTable: false,
  tablePosition: 'none',
  xAxis: {
    label: 'Quantity (millions of bottles per day)',
    min: 7,
    max: 13,
    ticks: [7, 8, 9, 10, 11, 12, 13],
    tickFormat: 'integer',
  },
  graphArrowsEnabled: true,
  graphArrowCalloutsEnabled: false,
  yAxis: {
    label: 'Price (dollars per bottle)',
    min: 0,
    max: 2.5,
    ticks: [0, 0.5, 1, 1.5, 2, 2.5],
    tickFormat: 'decimal-2',
    titleRotation: 0,
    titleAboveMaxTick: true,
    titleOffsetX: -8,
    titleOffsetY: -14,
  },
  curves: [
    {
      id: 'demand',
      label: 'Demand',
      curveType: 'throughPoints',
      params: {
        points: [
          { x: 8.5, y: 1.85 },
          { x: 10.5, y: 1.25 },
          { x: 11, y: 0.75 },
          { x: 12.3, y: 0.52 },
        ],
      },
      colorRole: 'demand',
      visible: false,
      animated: false,
    },
    {
      id: 'supply-initial',
      label: 'S₀',
      curveType: 'throughPoints',
      params: {
        points: [
          { x: 8.5, y: 0.53 },
          { x: 10.5, y: 1.25 },
          { x: 11.7, y: 2.2 },
        ],
      },
      colorRole: 'demand',
      visible: false,
      animated: true,
    },
    {
      id: 'supply-decrease',
      label: 'S₁',
      curveType: 'throughPoints',
      params: {
        points: [
          { x: 7.5, y: 0.78 },
          { x: 9.5, y: 1.5 },
          { x: 10.7, y: 2.45 },
        ],
      },
      colorRole: 'supplyInitial',
      visible: false,
      animated: false,
      morphFromCurveId: 'supply-initial',
    },
    {
      id: 'supply-increase',
      label: 'S₂',
      curveType: 'throughPoints',
      params: {
        points: [
          { x: 9.5, y: 0.28 },
          { x: 11.5, y: 1 },
          { x: 12.7, y: 1.95 },
        ],
      },
      colorRole: 'supplyInitial',
      visible: false,
      animated: false,
      morphFromCurveId: 'supply-initial',
    },
  ],
  equilibria: [
    {
      id: 'market',
      demandCurveId: 'demand',
      supplyCurveId: 'supply-initial',
      point: { x: 10.5, y: 1.25 },
      colorRole: 'curveRed',
      pointStroke: '#ffffff',
      pointStrokeWidth: 1,
    },
  ],
  exploreLayers: ['supply-initial', 'supply-decrease', 'supply-increase'],
  graphArrows: [
    {
      id: 'quantity-supplied-decreases',
      belowCurveId: 'supply-initial',
      from: { x: 10.1, y: 1.07 },
      to: { x: 9, y: 0.69 },
      label: 'Quantity\nsupplied\ndecreases',
      calloutColorRole: 'calloutCream',
      strokeColorRole: 'quantityDemandedIncreases',
      borderColorRole: 'demand',
      borderWidth: 0.6,
      labelOffset: { x: 7.7, y: 1.25 },
      labelOffsetBuild: { x: 8.5, y: 1.25 },
    },
    {
      id: 'quantity-supplied-increases',
      belowCurveId: 'supply-initial',
      from: { x: 10.9, y: 1.5 },
      to: { x: 11.6, y: 2.11 },
      label: 'Quantity\nsupplied\nincreases',
      calloutColorRole: 'calloutCream',
      strokeColorRole: 'quantityDemandedIncreases',
      borderColorRole: 'demand',
      borderWidth: 0.6,
      labelOffset: { x: 11.15, y: 1.55 },
      labelOffsetBuild: { x: 10, y: 1.75 },
    },
    {
      id: 'supply-decreases',
      from: { x: 10.32, y: 1.25 },
      to: { x: 8.99, y: 1.25 },
      label: 'Supply\ndecreases',
      calloutColorRole: 'calloutCream',
      strokeGradient: { fromColorRole: 'demand', toColorRole: 'supplyInitial' },
      borderWidth: 0,
      fillOpacity: 1,
      labelOffset: { x: 9, y: 1.75 },
      labelOffsetBuild: { x: 8.5, y: 1.6 },
    },
    {
      id: 'supply-increases',
      from: { x: 10.68, y: 1.25 },
      to: { x: 11.8, y: 1.25 },
      label: 'Supply\nincreases',
      calloutColorRole: 'calloutCream',
      strokeGradient: { fromColorRole: 'demand', toColorRole: 'supplyInitial' },
      borderWidth: 0,
      fillOpacity: 1,
      labelOffset: { x: 12, y: 0.75 },
      labelOffsetBuild: { x: 12, y: 0.75 },
    },
  ],
  buildSteps: [
    {
      id: 'step-1',
      title: 'Change in quantity supplied versus change in supply',
      description:
        'The graph illustrates the effects of changes in all the influences on selling plans and highlights the distinction between a change in the quantity supplied and a change in supply.',
      visibleLayers: ['supply-initial'],
    },
    {
      id: 'step-2',
      title: 'A decrease in the quantity supplied',
      description:
        'A fall in the price of the good, other things remaining the same, decreases the quantity supplied and creates a movement downward along the supply curve.',
      visibleLayers: ['supply-initial'],
      visibleAnnotations: ['quantity-supplied-decreases'],
      graphArrowCalloutsEnabled: true,
    },
    {
      id: 'step-3',
      title: 'An increase in the quantity supplied',
      description:
        'A rise in the price of the good, other things remaining the same, increases the quantity supplied and creates a movement upward along the supply curve.',
      visibleLayers: ['supply-initial'],
      visibleAnnotations: ['quantity-supplied-decreases', 'quantity-supplied-increases'],
      graphArrowCalloutsEnabled: true,
    },
    {
      id: 'step-4',
      title: 'A decrease in supply',
      description:
        'Supply decreases and the supply curve shifts leftward (from S₀ to S₁) if:\n\n• The price of a substitute in production rises.\n• The price of a complement in production falls.\n• A resource price or other input price rises.\n• The price of the good is expected to rise.\n• The number of sellers decreases.\n• Productivity decreases.',
      visibleLayers: ['supply-initial', 'supply-decrease'],
      showEquilibrium: true,
      visibleEquilibria: ['market'],
      visibleAnnotations: ['supply-decreases'],
      graphArrowCalloutsEnabled: true,
    },
    {
      id: 'step-5',
      title: 'An increase in supply',
      description:
        'Supply increases and the supply curve shifts rightward (from S₀ to S₂) if:\n\n• The price of a substitute in production falls.\n• The price of a complement in production rises.\n• A resource price or other input price falls.\n• The price of the good is expected to fall.\n• The number of sellers increases.\n• Productivity increases.',
      visibleLayers: ['supply-initial', 'supply-decrease', 'supply-increase'],
      showEquilibrium: true,
      visibleEquilibria: ['market'],
      visibleAnnotations: ['supply-decreases', 'supply-increases'],
      graphArrowCalloutsEnabled: true,
    },
    {
      id: 'step-6',
      title: 'Summary',
      description:
        'Movements along S₀ are changes in quantity supplied (price changes, other things equal). Shifts from S₀ to S₁ or S₂ are changes in supply when a non-price determinant changes.',
      visibleLayers: ['supply-initial', 'supply-decrease', 'supply-increase'],
      showEquilibrium: true,
      visibleEquilibria: ['market'],
      visibleAnnotations: [
        'quantity-supplied-decreases',
        'quantity-supplied-increases',
        'supply-decreases',
        'supply-increases',
      ],
    },
  ],
  animationSteps: [
    { id: 'animate-1', title: 'S₀', durationMs: 1000, layerIds: ['supply-initial'] },
    {
      id: 'animate-2',
      title: 'Movements along S₀',
      durationMs: 1200,
      annotationIds: ['quantity-supplied-decreases', 'quantity-supplied-increases'],
    },
    { id: 'animate-3', title: 'S₁ shift', durationMs: 1200, layerIds: ['supply-decrease'] },
    { id: 'animate-4', title: 'S₂ shift', durationMs: 1200, layerIds: ['supply-increase'] },
    {
      id: 'animate-5',
      title: 'Shift arrows',
      durationMs: 1000,
      annotationIds: ['supply-decreases', 'supply-increases'],
    },
  ],
  curveLabels: [
    { curveId: 'supply-initial', text: 'S₀', x: 11.7, y: 2.05, anchor: 'start', offsetX: 0.22 },
    { curveId: 'supply-decrease', text: 'S₁', x: 10.7, y: 2.35, anchor: 'start', offsetX: 0.22 },
    { curveId: 'supply-increase', text: 'S₂', x: 12.7, y: 1.85, anchor: 'start', offsetX: 0.22 },
  ],
  modeContent: {
    book: 'Use Build to step through the four textbook cases: quantity supplied down and up along S₀, then supply decreases (S₁) and supply increases (S₂).',
    animate: 'Watch S₀, movements along the curve, and left/right shifts to S₁ and S₂.',
    build: 'Click Next to reveal each case from the textbook—movements along S₀, then shifts to S₁ and S₂, ending with the full figure.',
  },
};
